version: "3"

services:
  server:
    build: server/
    
    command: python ./server.py
    
    ports:
      - 1101:1001
    
  bridge:
    build: bridge/
    
    command: python ./bridge.py
    
    ports:
      - 1102:1001
    
    depends_on:
      - server
  
  client:
    build: client/
    
    command: python ./client.py
    
    depends_on:
      - bridge
